" aibox.vim — generated by aibox CLI from the active theme palette.
" Do NOT edit; re-run `aibox theme` to regenerate.

hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "aibox"
set background=dark

" ── UI chrome ──────────────────────────────────────────────────────────────
hi Normal         guifg=#C9D1D9     guibg=#0D1117     ctermfg=NONE ctermbg=NONE
hi NormalNC       guifg=#C9D1D9     guibg=#0D1117
hi LineNr         guifg=#8B949E  guibg=#0D1117
hi CursorLineNr   guifg=#58A6FF guibg=#313244 gui=bold
hi CursorLine     guibg=#313244
hi CursorColumn   guibg=#313244
hi ColorColumn    guibg=#313244
hi VertSplit      guifg=#8B949E  guibg=#0D1117
hi WinSeparator   guifg=#8B949E  guibg=#0D1117
hi StatusLine     guifg=#0D1117     guibg=#58A6FF gui=bold
hi StatusLineNC   guifg=#8B949E  guibg=#313244
hi TabLine        guifg=#8B949E  guibg=#313244
hi TabLineFill    guibg=#0D1117
hi TabLineSel     guifg=#0D1117     guibg=#58A6FF gui=bold
hi SignColumn     guifg=#8B949E  guibg=#0D1117
hi FoldColumn     guifg=#8B949E  guibg=#0D1117
hi Folded         guifg=#8B949E  guibg=#313244
hi NonText        guifg=#8B949E
hi EndOfBuffer    guifg=#0D1117     guibg=#0D1117
hi SpecialKey     guifg=#8B949E
hi MatchParen     guifg=#58A6FF guibg=#313244 gui=bold,underline
hi Conceal        guifg=#8B949E  guibg=#0D1117
hi Directory      guifg=#58A6FF gui=bold

" ── Selection / search ────────────────────────────────────────────────────
hi Visual         guibg=#313244
hi VisualNOS      guibg=#313244
hi Search         guifg=#0D1117     guibg=#D29922 gui=bold
hi IncSearch      guifg=#0D1117     guibg=#DB6D28 gui=bold
hi CurSearch      guifg=#0D1117     guibg=#58A6FF gui=bold
hi QuickFixLine   guibg=#313244 gui=bold

" ── Popup menu ────────────────────────────────────────────────────────────
hi Pmenu          guifg=#C9D1D9     guibg=#313244
hi PmenuSel       guifg=#0D1117     guibg=#58A6FF gui=bold
hi PmenuSbar      guibg=#313244
hi PmenuThumb     guibg=#8B949E
hi WildMenu       guifg=#0D1117     guibg=#58A6FF gui=bold

" ── Messages ──────────────────────────────────────────────────────────────
hi ErrorMsg       guifg=#F85149    gui=bold
hi WarningMsg     guifg=#D29922
hi ModeMsg        guifg=#58A6FF gui=bold
hi MoreMsg        guifg=#3FB950
hi Question       guifg=#58A6FF
hi Title          guifg=#58A6FF gui=bold

" ── Syntax (linked groups) ────────────────────────────────────────────────
hi Comment        guifg=#8B949E    gui=italic
hi Constant       guifg=#DB6D28
hi String         guifg=#3FB950
hi Character      guifg=#3FB950
hi Number         guifg=#DB6D28
hi Boolean        guifg=#DB6D28
hi Float          guifg=#DB6D28
hi Identifier     guifg=#C9D1D9
hi Function       guifg=#58A6FF
hi Statement      guifg=#F85149
hi Conditional    guifg=#F85149
hi Repeat         guifg=#F85149
hi Label          guifg=#D29922
hi Operator       guifg=#79C0FF
hi Keyword        guifg=#F85149
hi Exception      guifg=#F85149
hi PreProc        guifg=#D29922
hi Include        guifg=#F85149
hi Define         guifg=#F85149
hi Macro          guifg=#58A6FF
hi PreCondit      guifg=#D29922
hi Type           guifg=#D29922
hi StorageClass   guifg=#D29922
hi Structure      guifg=#D29922
hi Typedef        guifg=#D29922
hi Special        guifg=#79C0FF
hi SpecialChar    guifg=#DB6D28
hi Tag            guifg=#58A6FF
hi Delimiter      guifg=#C9D1D9
hi SpecialComment guifg=#8B949E    gui=italic
hi Debug          guifg=#DB6D28
hi Underlined     guifg=#58A6FF   gui=underline
hi Ignore         guifg=#8B949E
hi Error          guifg=#F85149      gui=bold
hi Todo           guifg=#D29922   guibg=#313244 gui=bold

" ── Diff ──────────────────────────────────────────────────────────────────
hi DiffAdd        guifg=#3FB950    guibg=#0D1117
hi DiffChange     guifg=#D29922   guibg=#0D1117
hi DiffDelete     guifg=#F85149      guibg=#0D1117
hi DiffText       guifg=#58A6FF   guibg=#0D1117    gui=bold
hi diffAdded      guifg=#3FB950
hi diffRemoved    guifg=#F85149
hi diffChanged    guifg=#D29922
hi diffFile       guifg=#58A6FF   gui=bold
hi diffNewFile    guifg=#3FB950    gui=bold
hi diffOldFile    guifg=#F85149      gui=bold
hi diffLine       guifg=#8B949E

" ── Spelling ──────────────────────────────────────────────────────────────
hi SpellBad       gui=undercurl guisp=#F85149
hi SpellCap       gui=undercurl guisp=#D29922
hi SpellLocal     gui=undercurl guisp=#79C0FF
hi SpellRare      gui=undercurl guisp=#B87391

" ── Git plugins / gitgutter / signify ────────────────────────────────────
hi GitGutterAdd          guifg=#3FB950    guibg=#0D1117
hi GitGutterChange       guifg=#D29922   guibg=#0D1117
hi GitGutterDelete       guifg=#F85149      guibg=#0D1117
hi GitGutterChangeDelete guifg=#DB6D28   guibg=#0D1117
hi SignifySignAdd        guifg=#3FB950    guibg=#0D1117
hi SignifySignChange     guifg=#D29922   guibg=#0D1117
hi SignifySignDelete     guifg=#F85149      guibg=#0D1117

" ── Markdown ──────────────────────────────────────────────────────────────
hi link markdownH1        Title
hi link markdownH2        Title
hi link markdownH3        Title
hi link markdownH4        Title
hi link markdownCode      String
hi link markdownCodeBlock String
hi link markdownLinkText  Function
hi markdownUrl   guifg=#79C0FF  gui=underline

" ── Vim help ──────────────────────────────────────────────────────────────
hi link helpHyperTextEntry Underlined
hi link helpHyperTextJump  Underlined
hi link helpHeader         Title
hi link helpExample        String
hi link helpOption         Type
hi link helpVim            Identifier

" ── Misc plugins ──────────────────────────────────────────────────────────
hi link NvimTreeFolderName Directory
hi link NvimTreeRootFolder Title
hi link TelescopeBorder    FloatBorder
hi FloatBorder    guifg=#8B949E    guibg=#0D1117
hi NormalFloat    guifg=#C9D1D9       guibg=#313244
