#!/usr/bin/env bash
# tmux-powerkit theme — generated by aibox CLI from the active theme palette.
# Loaded via @powerkit_theme "custom" + @powerkit_custom_theme_path.
# Do NOT edit; re-run `aibox theme` to regenerate.

declare -gA THEME_COLORS=(
    # Core
    [background]="#0D1117"

    # Status bar
    [statusbar-bg]="#313244"
    [statusbar-fg]="#C9D1D9"

    # Session (status-left)
    [session-bg]="#58A6FF"
    [session-fg]="#0D1117"
    [session-prefix-bg]="#F85149"
    [session-copy-bg]="#79C0FF"
    [session-search-bg]="#D29922"
    [session-command-bg]="#B87391"

    # Windows
    [window-active-base]="#58A6FF"
    [window-active-style]="bold"
    [window-inactive-base]="#8B949E"
    [window-inactive-style]="none"
    [window-activity-style]="italics"
    [window-bell-style]="bold"
    [window-zoomed-bg]="#79C0FF"

    # Panes
    [pane-border-active]="#58A6FF"
    [pane-border-inactive]="#8B949E"

    # Health / state segments (chevron color rotation source)
    [ok-base]="#799ABF"
    [good-base]="#3FB950"
    [info-base]="#79C0FF"
    [warning-base]="#D29922"
    [error-base]="#F85149"
    [disabled-base]="#8B949E"

    # Messages
    [message-bg]="#313244"
    [message-fg]="#C9D1D9"

    # Popup & menu
    [popup-bg]="#313244"
    [popup-fg]="#C9D1D9"
    [popup-border]="#58A6FF"
    [menu-bg]="#313244"
    [menu-fg]="#C9D1D9"
    [menu-selected-bg]="#58A6FF"
    [menu-selected-fg]="#0D1117"
    [menu-border]="#58A6FF"
)

# Extra slots some plugins read directly — also derived from the palette so
# every chevron lands on a known-good bg.
declare -gA THEME_EXTRA=(
    [orange]="#DB6D28"
    [magenta]="#B87391"
    [surface]="#313244"
)
