use anyhow::{Context, Result};
use minijinja::context;
use semver::Version;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Component, Path, PathBuf};

use crate::config::{AiHarness, AiboxConfig, BaseImage, McpGatewayMode};
use crate::output;

fn write_if_changed(path: &Path, content: &str) -> Result<bool> {
    crate::context::write_if_changed(path, content)
}

// Header is intentionally version-free so a clean container rebuild on a new
// CLI version doesn't dirty `git status` for files whose semantic content
// hasn't changed. The CLI version that performed the install is recorded in
// aibox.lock (the canonical place); stamping it into every generated file's
// header just produced rebuild churn. See v0.18.7 devcontainer drift fix.
const HEADER_TEMPLATE: &str = "# Generated by aibox — do not edit manually.\n# To modify, edit aibox.toml and run: aibox apply\n";
const IMAGE_TAG_RUNTIME_CUTOFF_MINOR: u64 = 27;

fn dockerfile_image_tag(base: &BaseImage, version: &str) -> String {
    match version {
        "latest" if current_cli_uses_runtime_image_tag() => {
            format!("base-{}-runtime-latest", base)
        }
        "latest" => format!("base-{}-latest", base),
        _ if should_use_runtime_image_tag(version) => format!("base-{}-runtime-v{}", base, version),
        _ => format!("base-{}-v{}", base, version),
    }
}

fn current_cli_uses_runtime_image_tag() -> bool {
    should_use_runtime_image_tag(env!("CARGO_PKG_VERSION"))
}

fn should_use_runtime_image_tag(version: &str) -> bool {
    let Ok(parsed) = semver::Version::parse(version) else {
        return false;
    };

    parsed.major > 0 || parsed.minor >= IMAGE_TAG_RUNTIME_CUTOFF_MINOR
}

/// Create a minijinja environment with embedded templates.
fn create_template_env() -> minijinja::Environment<'static> {
    let mut env = minijinja::Environment::new();
    env.set_trim_blocks(true);
    env.set_lstrip_blocks(true);
    env.add_template("Dockerfile", include_str!("templates/Dockerfile.j2"))
        .expect("Failed to add Dockerfile template");
    env.add_template(
        "docker-compose.yml",
        include_str!("templates/docker-compose.yml.j2"),
    )
    .expect("Failed to add docker-compose template");
    env
}

pub(crate) fn sanitize_compose_project_name(name: &str) -> String {
    let mut sanitized = String::new();
    let mut last_was_separator = false;

    for ch in name.chars().map(|ch| ch.to_ascii_lowercase()) {
        if ch.is_ascii_alphanumeric() {
            sanitized.push(ch);
            last_was_separator = false;
        } else if !last_was_separator && !sanitized.is_empty() {
            sanitized.push('-');
            last_was_separator = true;
        }
    }

    while sanitized.ends_with('-') {
        sanitized.pop();
    }

    if sanitized.is_empty() {
        "aibox".to_string()
    } else {
        sanitized
    }
}

fn project_path(path: &str) -> PathBuf {
    PathBuf::from(path)
}

fn parent_dir(path: &Path) -> &Path {
    path.parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."))
}

fn normalized_relative_components(path: &Path) -> Vec<String> {
    path.components()
        .filter_map(|component| match component {
            Component::Normal(value) => Some(value.to_string_lossy().into_owned()),
            Component::CurDir => None,
            _ => Some(component.as_os_str().to_string_lossy().into_owned()),
        })
        .collect()
}

fn relative_path(from_dir: &Path, target: &Path) -> String {
    if target.is_absolute() {
        return target.to_string_lossy().into_owned();
    }
    let from = normalized_relative_components(from_dir);
    let to = normalized_relative_components(target);
    let common = from
        .iter()
        .zip(to.iter())
        .take_while(|(a, b)| a == b)
        .count();
    let mut result = Vec::new();
    for _ in common..from.len() {
        result.push("..".to_string());
    }
    result.extend(to.into_iter().skip(common));
    if result.is_empty() {
        ".".to_string()
    } else {
        result.join("/")
    }
}

/// Generate all devcontainer files from the config.
pub fn generate_all(config: &AiboxConfig) -> Result<()> {
    let dockerfile_path = project_path(&config.container.paths.dockerfile);
    let docker_compose_path = project_path(&config.container.paths.docker_compose);
    let devcontainer_json_path = project_path(&config.container.paths.devcontainer_json);
    for path in [
        &dockerfile_path,
        &docker_compose_path,
        &devcontainer_json_path,
    ] {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("Failed to create {}", parent.display()))?;
        }
    }

    output::info("Generating devcontainer files...");

    let mut effective_config = config.clone();
    if effective_config.container.image.version == "latest" {
        let flavor = effective_config.container.image.base.to_string();
        match crate::update::fetch_latest_image_version(&flavor) {
            Ok(v) => {
                effective_config.container.image.version = image_version_for_generation(v);
                effective_config.image.version = effective_config.container.image.version.clone();
            }
            Err(e) => {
                crate::output::warn(&format!(
                    "[container.image].release_version = \"latest\" but image version resolution failed during generation: {}. \
                     Generated files may reference an invalid tag. Consider re-running with network access or pinning an explicit version.",
                    e
                ));
            }
        }
    }

    // Create template environment once and reuse for all template-based files
    let env = create_template_env();

    if generate_dockerfile(&effective_config, &dockerfile_path, &env)? {
        output::ok(&format!("Generated {}", dockerfile_path.display()));
    }

    if generate_docker_compose(&effective_config, &docker_compose_path, &env)? {
        output::ok(&format!("Generated {}", docker_compose_path.display()));
    }

    if generate_devcontainer_json(&effective_config, &devcontainer_json_path)? {
        output::ok(&format!("Generated {}", devcontainer_json_path.display()));
    }

    Ok(())
}

pub(crate) fn image_version_for_generation(published_latest: Version) -> String {
    published_latest.to_string()
}

/// Generate the Dockerfile. Returns true if file was written.
fn generate_dockerfile(
    config: &AiboxConfig,
    path_or_dir: &Path,
    env: &minijinja::Environment<'static>,
) -> Result<bool> {
    let header = HEADER_TEMPLATE.to_string();
    let dockerfile_path = if path_or_dir.is_dir() {
        path_or_dir.join("Dockerfile")
    } else {
        path_or_dir.to_path_buf()
    };
    let dockerfile_local_path = if path_or_dir.is_dir() {
        path_or_dir.join("Dockerfile.local")
    } else {
        project_path(&config.container.paths.dockerfile_local)
    };

    // Read Dockerfile.local if it exists
    let local_content = {
        match fs::read_to_string(&dockerfile_local_path) {
            Ok(raw) => {
                let trimmed = raw.trim_end_matches('\n');
                if trimmed.trim().is_empty() {
                    None
                } else {
                    Some(trimmed.to_string())
                }
            }
            Err(_) => None,
        }
    };

    let tmpl = env
        .get_template("Dockerfile")
        .context("Failed to load Dockerfile template")?;

    // Build addon Dockerfile content (builder stages + runtime commands).
    // AI providers are resolved into addons at config load time, so they
    // flow through this pipeline automatically — no hardcoded template logic.
    let addon_output = crate::addons::generate_dockerfile_content(&config.addons)?;
    let addon_builder_stages = addon_output.builder_stages;
    let addon_commands = addon_output.runtime_commands;

    let content = tmpl
        .render(context! {
            header => header,
            registry => crate::config::IMAGE_REGISTRY,
            image_tag => dockerfile_image_tag(&config.container.image.base, &config.container.image.version),
            version => config.container.image.version,
            profile => config.aibox.profile.to_string(),
            addon_builder_stages => addon_builder_stages,
            addon_commands => addon_commands,
            local_content => local_content,
        })
        .context("Failed to render Dockerfile template")?;

    write_if_changed(&dockerfile_path, &content)
}

/// Generate docker-compose.yml. Returns true if file was written.
fn generate_docker_compose(
    config: &AiboxConfig,
    path_or_dir: &Path,
    env: &minijinja::Environment<'static>,
) -> Result<bool> {
    let header = HEADER_TEMPLATE.to_string();
    let workspace_dir = config.workspace_dir();
    let legacy_dir_arg = path_or_dir.is_dir();
    let compose_path = if path_or_dir.is_dir() {
        path_or_dir.join("docker-compose.yml")
    } else {
        path_or_dir.to_path_buf()
    };
    let compose_dir = parent_dir(&compose_path);

    // Compose paths must be relative to the compose file's directory.
    let host_root = config.host_root_dir();
    let host_root_str = if legacy_dir_arg && host_root.is_relative() {
        format!("../{}", host_root.to_string_lossy())
    } else if host_root.is_relative() {
        relative_path(compose_dir, &host_root)
    } else {
        host_root.to_string_lossy().into_owned()
    };

    // Build environment map (BTreeMap for sorted keys)
    let mut env_vars: BTreeMap<String, String> = BTreeMap::new();
    env_vars.insert("TZ".to_string(), "Europe/Berlin".to_string());
    env_vars.insert("LANG".to_string(), "en_US.UTF-8".to_string());
    env_vars.insert("COLORTERM".to_string(), "truecolor".to_string());
    env_vars.insert("TERM".to_string(), "xterm-256color".to_string());
    env_vars.insert("SHELL".to_string(), "/bin/bash".to_string());
    let audio = if config.container.audio.enabled {
        &config.container.audio
    } else {
        &config.audio
    };
    if audio.enabled {
        env_vars.insert("PULSE_SERVER".to_string(), audio.pulse_server.clone());
        env_vars.insert("AUDIODRIVER".to_string(), "pulseaudio".to_string());
    }

    let compose_override_path = if legacy_dir_arg {
        path_or_dir.join("docker-compose.override.yml")
    } else {
        project_path(&config.container.paths.docker_compose_override)
    };
    let codex_sandbox_seccomp = config.ai.harnesses.contains(&AiHarness::Codex)
        && !compose_override_declares_codex_seccomp(&compose_override_path, &config.container.name);

    // S5 — BR-SEC-HARDEN: require explicit consent before emitting seccomp=unconfined.
    if codex_sandbox_seccomp && !config.security.acknowledge_seccomp_unconfined {
        anyhow::bail!(
            "Codex sandbox requires seccomp=unconfined in the generated docker-compose.yml, \
             but explicit consent has not been given.\n\
             \n\
             To opt in, add the following to your aibox.toml:\n\
             \n\
             [security]\n\
             acknowledge_seccomp_unconfined = true\n\
             \n\
             This setting documents that you accept the reduced seccomp filtering \
             required for bubblewrap user-namespace sandboxing."
        );
    }

    // Container home path
    let container_home = config.container_home();

    // GIT_CONFIG_GLOBAL must use the container home path
    env_vars.insert(
        "GIT_CONFIG_GLOBAL".to_string(),
        format!("{}/.config/git/config", container_home),
    );

    // Merge user-defined environment variables from aibox.toml (shared, safe to
    // commit). Variables from .aibox-local.toml (credentials) are handled
    // separately below — they go to .aibox-local.env, not into docker-compose.yml.
    for (k, v) in &config.container.environment {
        if !config.local_env.contains_key(k) {
            env_vars.insert(k.clone(), v.clone());
        }
    }

    // Escape values for YAML double-quoted strings
    let escaped_env: BTreeMap<String, String> = env_vars
        .iter()
        .map(|(k, v)| {
            let escaped = v.replace('\\', "\\\\").replace('"', "\\\"");
            (k.clone(), escaped)
        })
        .collect();

    let env_keys: Vec<String> = escaped_env.keys().cloned().collect();

    // Write .aibox-local.env even when empty so docker-compose env_file
    // references are stable while secrets remain outside committed files.
    let local_env_sorted: BTreeMap<&String, &String> = config.local_env.iter().collect();
    let env_content: String = local_env_sorted
        .iter()
        .map(|(k, v)| format!("{}={}\n", k, v))
        .collect();
    let local_env_path = project_path(&config.container.paths.local_env);
    if let Some(parent) = local_env_path.parent()
        && !parent.as_os_str().is_empty()
    {
        fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create {}", parent.display()))?;
    }
    fs::write(&local_env_path, &env_content)
        .with_context(|| format!("Failed to write {}", local_env_path.display()))?;

    // Extra volumes from aibox.toml + .aibox-local.toml
    let extra_volumes = &config.container.extra_volumes;
    let runtime_home_mounts =
        crate::runtime_home::compose_runtime_home_mounts(config, &host_root_str);

    // Rust addon flag — drives cargo registry mounts in the template
    let compose_project_name = sanitize_compose_project_name(&config.container.name);
    let compose_image_name = format!("{}-devcontainer:latest", compose_project_name);
    let latex_preview_enabled = config.latex.preview.enabled && !config.latex.documents.is_empty();
    let latex_preview_documents = config
        .latex
        .documents
        .iter()
        .map(|document| {
            let stem = Path::new(&document.source)
                .file_stem()
                .unwrap_or_default()
                .to_string_lossy();
            serde_json::json!({
                "name": document.name,
                "source": document.source,
                "pdf": format!(
                    "/workspace/{}/{}.pdf",
                    document.output_dir.trim_end_matches('/'),
                    stem
                ),
            })
        })
        .collect::<Vec<_>>();
    let latex_preview_documents_json = serde_json::to_string(&latex_preview_documents)?
        .replace('\\', "\\\\")
        .replace('"', "\\\"");
    let latex_preview_preferred_document = config
        .latex
        .preview
        .document
        .as_deref()
        .or_else(|| {
            config
                .latex
                .documents
                .first()
                .map(|document| document.name.as_str())
        })
        .unwrap_or_default()
        .replace('\\', "\\\\")
        .replace('"', "\\\"");
    let latex_preview_bind: std::net::IpAddr = config
        .latex
        .preview
        .bind
        .parse()
        .expect("validated LaTeX preview bind address");
    let latex_preview_publish = match latex_preview_bind {
        std::net::IpAddr::V6(_) => format!(
            "[{}]:{}:8765",
            latex_preview_bind, config.latex.preview.port
        ),
        _ => format!("{}:{}:8765", latex_preview_bind, config.latex.preview.port),
    };

    let tmpl = env
        .get_template("docker-compose.yml")
        .context("Failed to load docker-compose template")?;
    let dockerfile_path = if legacy_dir_arg {
        path_or_dir.join("Dockerfile")
    } else {
        project_path(&config.container.paths.dockerfile)
    };
    let local_env_file = if legacy_dir_arg {
        "../.aibox-local.env".to_string()
    } else {
        relative_path(compose_dir, &local_env_path)
    };

    let content = tmpl
        .render(context! {
            header => header,
            project_name => compose_project_name,
            image_name => compose_image_name,
            name => config.container.name,
            hostname => config.container.hostname,
            user => config.container.user,
            workspace_dir => workspace_dir,
            host_root => host_root_str,
            container_home => container_home,
            dockerfile_path => if legacy_dir_arg {
                "Dockerfile".to_string()
            } else {
                relative_path(compose_dir, &dockerfile_path)
            },
            local_env_file => local_env_file,
            runtime_home_mounts => runtime_home_mounts,
            codex_sandbox_seccomp => codex_sandbox_seccomp,
            env_keys => env_keys,
            env_vals => escaped_env,
            extra_volumes => extra_volumes,
            latex_preview_enabled => latex_preview_enabled,
            latex_preview_documents_json => latex_preview_documents_json,
            latex_preview_preferred_document => latex_preview_preferred_document,
            latex_preview_publish => latex_preview_publish,
        })
        .context("Failed to render docker-compose template")?;

    write_if_changed(&compose_path, &content)
}

/// Generate devcontainer.json. Returns true if file was written.
fn generate_devcontainer_json(config: &AiboxConfig, path_or_dir: &Path) -> Result<bool> {
    let legacy_dir_arg = path_or_dir.is_dir();
    let devcontainer_json_path = if path_or_dir.is_dir() {
        path_or_dir.join("devcontainer.json")
    } else {
        path_or_dir.to_path_buf()
    };
    let name = &config.container.name;
    let addons = &config.addons;

    // Build extensions list
    let mut extensions: Vec<String> = vec![];
    if addons.has_python() {
        extensions.push("ms-python.python".to_string());
    }
    if addons.has_rust() {
        extensions.push("rust-lang.rust-analyzer".to_string());
    }
    if addons.has_latex() {
        extensions.push("james-yu.latex-workshop".to_string());
        extensions.push("mblode.zotero".to_string());
    }
    if addons.has_addon("typst") {
        extensions.push("myriad-dreamin.tinymist".to_string());
    }
    if addons.has_node() {
        extensions.push("dbaeumer.vscode-eslint".to_string());
    }
    if addons.has_addon("go") {
        extensions.push("golang.go".to_string());
    }

    // Build VS Code terminal profiles — include configured AI providers.
    // The tmux profile uses the layout from aibox.toml so VS Code terminals
    // match `aibox up`'s default.
    let layout = config.customization.tmux_layout().to_string();
    let mut terminal_profiles = serde_json::json!({
        "bash": {
            "path": "/bin/bash"
        },
        "tmux": {
            "path": "/bin/bash",
            "args": ["-lc", format!("exec ~/.config/tmux/layouts/{layout}.sh")]
        }
    });

    for provider in &config.ai.harnesses {
        // Cursor is a host-side IDE extension with no container binary.
        // All other providers have a container CLI installed by their addon.
        // Continue's binary is `cn` (not `continue`); use binary_name() for the path.
        if !provider.is_active() || matches!(provider, crate::config::AiProvider::Cursor) {
            continue;
        }
        let name = provider.binary_name();
        let path = format!("/usr/local/bin/{}", name);
        terminal_profiles
            .as_object_mut()
            .unwrap()
            .insert(name.to_string(), serde_json::json!({ "path": path }));
    }

    // Build VS Code settings — start with base, add flavor-specific
    let mut settings = serde_json::json!({
        "terminal.integrated.defaultProfile.linux": "bash",
        "terminal.integrated.fontFamily": "'FiraCode Nerd Font', 'Hack Nerd Font', 'JetBrainsMono Nerd Font', monospace",
        "terminal.integrated.profiles.linux": terminal_profiles
    });

    // LaTeX Workshop settings — matches proven setup from derived projects
    if addons.has_latex() {
        let latex_settings = serde_json::json!({
            "latex-workshop.latex.outDir": "./out",
            "latex-workshop.view.pdf.viewer": "tab",
            "latex-workshop.latex.tools": [
                {
                    "name": "latexmk-lualatex",
                    "command": "latexmk",
                    "args": [
                        "--shell-escape",
                        "-synctex=1",
                        "-interaction=nonstopmode",
                        "-file-line-error",
                        "-pdflatex=lualatex",
                        "-pdf",
                        "-aux-directory=./out",
                        "-output-directory=./out",
                        "%DOC%"
                    ]
                },
                {
                    "name": "latexmk-pdflatex",
                    "command": "latexmk",
                    "args": [
                        "-synctex=1",
                        "-interaction=nonstopmode",
                        "-file-line-error",
                        "-pdf",
                        "-aux-directory=./out",
                        "-output-directory=./out",
                        "%DOC%"
                    ]
                },
                {
                    "name": "biber",
                    "command": "biber",
                    "args": [
                        "--input-directory=out",
                        "--output-directory=out",
                        "%DOCFILE%"
                    ]
                }
            ],
            "latex-workshop.latex.recipes": [
                {
                    "name": "latexmk (lualatex)",
                    "tools": ["latexmk-lualatex"]
                },
                {
                    "name": "latexmk (pdflatex)",
                    "tools": ["latexmk-pdflatex"]
                },
                {
                    "name": "latexmk (lualatex) + biber",
                    "tools": ["latexmk-lualatex", "biber", "latexmk-lualatex"]
                }
            ],
            "latex-workshop.latex.autoBuild.run": "onSave",
            "latex-workshop.latex.clean.fileTypes": [
                "*.aux", "*.bbl", "*.blg", "*.fdb_latexmk", "*.fls",
                "*.log", "*.out", "*.synctex.gz", "*.toc", "*.lof",
                "*.lot", "*.nav", "*.snm", "*.vrb", "*.bcf", "*.run.xml"
            ]
        });
        for (k, v) in latex_settings.as_object().unwrap() {
            settings
                .as_object_mut()
                .unwrap()
                .insert(k.clone(), v.clone());
        }
    }

    // Detect docker-compose.override.yml — if present, VS Code needs both
    // files listed explicitly. Docker Compose CLI auto-merges overrides, but
    // devcontainer.json requires the array form to pick them up.
    let devcontainer_dir = parent_dir(&devcontainer_json_path);
    let compose_path = if path_or_dir.is_dir() {
        path_or_dir.join("docker-compose.yml")
    } else {
        project_path(&config.container.paths.docker_compose)
    };
    let compose_override_path = if path_or_dir.is_dir() {
        path_or_dir.join("docker-compose.override.yml")
    } else {
        project_path(&config.container.paths.docker_compose_override)
    };
    let compose_file: serde_json::Value = if legacy_dir_arg && compose_override_path.exists() {
        serde_json::json!(["docker-compose.yml", "docker-compose.override.yml"])
    } else if legacy_dir_arg {
        serde_json::json!("docker-compose.yml")
    } else if compose_override_path.exists() {
        serde_json::json!([
            relative_path(devcontainer_dir, &compose_path),
            relative_path(devcontainer_dir, &compose_override_path)
        ])
    } else {
        serde_json::json!(relative_path(devcontainer_dir, &compose_path))
    };

    // Use serde_json for proper JSON formatting
    let mut devcontainer = serde_json::json!({
        "name": name,
        "dockerComposeFile": compose_file,
        "service": name,
        "workspaceFolder": "/workspace",
        "overrideCommand": false,
        "remoteUser": config.container.user,
        "customizations": {
            "vscode": {
                "extensions": extensions,
                "settings": settings
            }
        }
    });

    // Insert postCreateCommand if configured
    let post_create_command = config
        .container
        .lifecycle
        .post_create_command
        .as_ref()
        .or(config.container.post_create_command.as_ref());
    if let Some(cmd) = post_create_command {
        devcontainer
            .as_object_mut()
            .unwrap()
            .insert("postCreateCommand".to_string(), serde_json::json!(cmd));
    }

    let mut post_start_commands: Vec<String> = Vec::new();

    // Network keepalive — lightweight DNS lookup every 2 min to prevent
    // OrbStack/VM NAT from dropping idle connections.
    if config.container.lifecycle.keepalive || config.container.keepalive {
        post_start_commands.push(
            "nohup bash -c 'while true; do nslookup example.com > /dev/null 2>&1; sleep 120; done' > /dev/null 2>&1 &"
                .to_string(),
        );
    }
    if should_start_processkit_gateway_daemon(config, devcontainer_dir) {
        let gateway = &config.mcp.gateway;
        let mut env = "UV_CACHE_DIR=/tmp/aibox/uv-cache PROCESSKIT_MCP_MODE=gateway".to_string();
        if gateway.lazy_catalog {
            env.push_str(
                " PROCESSKIT_GATEWAY_IMPORT_MODE=lazy-catalog PROCESSKIT_GATEWAY_LAZY=true",
            );
        }
        let catalog_command = if gateway.lazy_catalog {
            format!(
                "{env} uv run context/skills/processkit/processkit-gateway/mcp/server.py catalog --write >/tmp/aibox/processkit-gateway-catalog.log 2>&1 || true; "
            )
        } else {
            String::new()
        };
        let serve_command = format!(
            "{env} nohup uv run context/skills/processkit/processkit-gateway/mcp/server.py serve --transport streamable-http --host {} --port {} >/tmp/aibox/processkit-gateway.log 2>&1 &",
            gateway.host, gateway.port
        );
        post_start_commands.push(format!(
            "if ! pgrep -f 'processkit-gateway/mcp/server.py.*streamable-http' >/dev/null 2>&1; then mkdir -p /tmp/aibox/uv-cache; (cd /workspace && {catalog_command}{serve_command}); fi"
        ));
    }
    if !post_start_commands.is_empty() {
        devcontainer.as_object_mut().unwrap().insert(
            "postStartCommand".to_string(),
            serde_json::json!(post_start_commands.join("; ")),
        );
    }

    // Prevent VS Code from auto-forwarding the PulseAudio port (fixes #11)
    let audio = if config.container.audio.enabled {
        &config.container.audio
    } else {
        &config.audio
    };
    if audio.enabled {
        // Extract port from pulse_server string (e.g., "tcp:host.docker.internal:4714")
        let port = audio.pulse_server.rsplit(':').next().unwrap_or("4714");
        devcontainer.as_object_mut().unwrap().insert(
            "portsAttributes".to_string(),
            serde_json::json!({
                port: { "onAutoForward": "ignore" }
            }),
        );
    }

    // Serialize with pretty formatting
    let json_str = serde_json::to_string_pretty(&devcontainer)
        .context("Failed to serialize devcontainer.json")?;

    // Add the header as a comment at the top (JSON doesn't support comments,
    // but devcontainer.json does via jsonc). v0.18.7: version-free header to
    // avoid rebuild churn (see HEADER_TEMPLATE comment).
    let header = "// Generated by aibox — do not edit manually.\n// To modify, edit aibox.toml and run: aibox apply\n".to_string();
    let _ = config; // version no longer interpolated; placeholder reference.

    write_if_changed(
        &devcontainer_json_path,
        &format!("{}{}\n", header, json_str),
    )
}

/// Public wrapper around `compose_override_declares_codex_seccomp` for callers
/// outside this module (e.g., the apply consent gate in container.rs).
pub fn compose_override_declares_codex_seccomp_pub(
    override_path: &Path,
    service_name: &str,
) -> bool {
    compose_override_declares_codex_seccomp(override_path, service_name)
}

fn compose_override_declares_codex_seccomp(override_path: &Path, service_name: &str) -> bool {
    let Ok(content) = fs::read_to_string(override_path) else {
        return false;
    };
    let Ok(compose) = serde_yaml::from_str::<serde_yaml::Value>(&content) else {
        return false;
    };
    compose_services(&compose).is_some_and(|services| {
        services
            .get(serde_yaml::Value::String(service_name.to_string()))
            .is_some_and(|service| {
                service
                    .get("security_opt")
                    .is_some_and(|value| yaml_value_contains_ci(value, "seccomp=unconfined"))
            })
    })
}

fn compose_services(compose: &serde_yaml::Value) -> Option<&serde_yaml::Mapping> {
    compose.get("services")?.as_mapping()
}

fn yaml_value_contains_ci(value: &serde_yaml::Value, needle: &str) -> bool {
    if let Some(text) = value.as_str() {
        return text.eq_ignore_ascii_case(needle);
    }
    value
        .as_sequence()
        .map(|items| {
            items.iter().any(|item| {
                item.as_str()
                    .map(|text| text.eq_ignore_ascii_case(needle))
                    .unwrap_or(false)
            })
        })
        .unwrap_or(false)
}

fn should_start_processkit_gateway_daemon(config: &AiboxConfig, _devcontainer_dir: &Path) -> bool {
    if !config.processkit_enabled() {
        return false;
    }
    match config.mcp.gateway.mode {
        McpGatewayMode::DaemonProxy => true,
        // processkit v0.25.4 made stdio-proxy own local daemon startup by
        // default. In auto mode, prefer that self-starting proxy over a
        // devcontainer postStartCommand that can race MCP client startup.
        McpGatewayMode::Auto
        | McpGatewayMode::Granular
        | McpGatewayMode::Stdio
        | McpGatewayMode::Aggregate
        | McpGatewayMode::LazyAggregate => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::*;
    use serial_test::serial;

    fn test_env() -> minijinja::Environment<'static> {
        create_template_env()
    }

    fn addons_with(names: &[&str]) -> crate::config::AddonsSection {
        use crate::config::{AddonToolsSection, AddonsSection};
        use std::collections::HashMap;
        let mut addons = HashMap::new();
        for name in names {
            addons.insert(
                name.to_string(),
                AddonToolsSection {
                    tools: HashMap::new(),
                    ..Default::default()
                },
            );
        }
        AddonsSection { addons }
    }

    fn ensure_addons_loaded() {
        let addons_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .join("addons");
        let _ = crate::addon_loader::init_from_dir(&addons_dir);
    }

    fn make_config(addon_names: &[&str], audio_enabled: bool) -> AiboxConfig {
        ensure_addons_loaded();
        let mut config = crate::config::test_config();
        config.container.image.version = "1.2.3".to_string();
        config.image.version = "1.2.3".to_string();
        config.container.name = "test-ctr".to_string();
        config.container.hostname = "test-host".to_string();
        config.addons = addons_with(addon_names);
        config.audio = AudioSection {
            enabled: audio_enabled,
            pulse_server: "tcp:localhost:4714".to_string(),
            ..AudioSection::default()
        };
        config
    }

    fn in_temp_dir<F: FnOnce()>(f: F) {
        let dir = tempfile::tempdir().unwrap();
        let original = std::env::current_dir().unwrap();
        std::env::set_current_dir(dir.path()).unwrap();
        f();
        std::env::set_current_dir(original).unwrap();
    }

    #[test]
    fn generate_all_creates_three_files() {
        let dir = tempfile::tempdir().unwrap();
        let devcontainer = dir.path().join(".devcontainer");
        // We need to run generate functions directly on the temp dir
        // Since generate_all uses relative paths, we test the individual generators
        fs::create_dir_all(&devcontainer).unwrap();
        let config = make_config(&[], false);
        generate_dockerfile(&config, &devcontainer, &test_env()).unwrap();
        generate_docker_compose(&config, &devcontainer, &test_env()).unwrap();
        generate_devcontainer_json(&config, &devcontainer).unwrap();

        assert!(devcontainer.join("Dockerfile").exists());
        assert!(devcontainer.join("docker-compose.yml").exists());
        assert!(devcontainer.join("devcontainer.json").exists());
    }

    #[test]
    fn image_version_for_generation_uses_published_image_version() {
        let published = semver::Version::parse("0.24.3").unwrap();
        let selected = image_version_for_generation(published);
        assert_eq!(
            selected, "0.24.3",
            "image generation must not couple a newer CLI version to an unpublished base image tag"
        );
    }

    #[test]
    fn image_version_for_generation_preserves_prerelease_tag() {
        let published = semver::Version::parse("1.0.0-alpha.1").unwrap();
        let selected = image_version_for_generation(published);
        assert_eq!(
            selected, "1.0.0-alpha.1",
            "image generation must preserve the exact published GHCR tag"
        );
    }

    #[test]
    fn dockerfile_contains_correct_from_image() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&["python"], false);
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        let image_tag = dockerfile_image_tag(
            &config.container.image.base,
            &config.container.image.version,
        );
        assert!(
            content.contains(&format!(
                "FROM {}:{} AS aibox",
                crate::config::IMAGE_REGISTRY,
                image_tag
            )),
            "Dockerfile should reference base-debian image with correct tag format and stage alias"
        );
        assert!(content.contains("LABEL aibox.version=\"1.2.3\""));
        assert!(content.contains("LABEL aibox.profile=\"human-dev\""));
    }

    #[test]
    fn dockerfile_uses_legacy_tag_family_for_0_26_series() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&["python"], false);
        config.container.image.version = "0.26.9".to_string();
        config.image.version = config.container.image.version.clone();
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();

        assert!(
            content.contains("FROM ghcr.io/projectious-work/aibox:base-debian-v0.26.9 AS aibox"),
            "0.26.x projects must continue using legacy base image tag family"
        );
    }

    #[test]
    fn image_tag_prefers_runtime_family_post_cutover() {
        assert_eq!(
            dockerfile_image_tag(&BaseImage::Debian, "1.2.3"),
            "base-debian-runtime-v1.2.3"
        );
        assert_eq!(
            dockerfile_image_tag(&BaseImage::Debian, "0.27.0"),
            "base-debian-runtime-v0.27.0"
        );
        assert_eq!(
            dockerfile_image_tag(&BaseImage::Debian, "0.26.3"),
            "base-debian-v0.26.3"
        );
    }

    #[test]
    fn latest_tag_family_follows_current_cli_minor_cutover() {
        let expected = if current_cli_uses_runtime_image_tag() {
            "base-debian-runtime-latest"
        } else {
            "base-debian-latest"
        };

        assert_eq!(dockerfile_image_tag(&BaseImage::Debian, "latest"), expected);
    }

    #[test]
    fn dockerfile_exports_shell_and_repairs_cache_home() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&["python"], false);
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();

        assert!(content.contains("ENV SHELL=/bin/bash"));
        assert!(
            content.contains("ENV UV_CACHE_DIR=/tmp/aibox/uv-cache")
                && content.contains("mkdir -p /home/aibox/.cache/starship /home/aibox/.cache/uv")
                && content.contains("/tmp/aibox/uv-cache")
                && content.contains("chown -R aibox:aibox /home/aibox/.cache /tmp/aibox"),
            "project Dockerfiles should repair cache-home and uv cache ownership for older base images:\n{content}"
        );
    }

    #[test]
    fn dockerfile_lazygit_disablement_cleanup_does_not_purge_unknown_package() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&["git-ui"], false);
        config
            .addons
            .addons
            .get_mut("git-ui")
            .unwrap()
            .tools
            .insert(
                "lazygit".to_string(),
                crate::config::ToolEntry {
                    version: None,
                    enabled: Some(false),
                },
            );

        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();

        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            content.contains("dpkg-query -W -f='${Status}' lazygit"),
            "disabled lazygit cleanup should only purge when dpkg reports an installed package:\n{content}"
        );
        assert!(
            content.contains("rm -f /usr/local/bin/lazygit /usr/bin/lazygit"),
            "disabled lazygit cleanup should remove binaries copied into older base images:\n{content}"
        );
        assert!(
            !content.contains("RUN apt-get purge -y --auto-remove lazygit"),
            "disabled lazygit cleanup must not fail when lazygit is not an apt package:\n{content}"
        );
    }

    #[test]
    fn compose_contains_container_name_and_hostname() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains("name: test-ctr"));
        assert!(content.contains("image: test-ctr-devcontainer:latest"));
        assert!(content.contains("container_name: test-ctr"));
        assert!(content.contains("hostname: test-host"));
        assert!(content.contains("user: root"));
    }

    #[test]
    fn compose_latex_preview_sidecar_is_conditional_and_hardened() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.latex.preview.enabled = true;
        config.latex.documents = vec![
            crate::config::LatexDocument {
                name: "overview".into(),
                source: "docs/overview.tex".into(),
                output_dir: ".latex-cache/overview".into(),
            },
            crate::config::LatexDocument {
                name: "appendix".into(),
                source: "docs/appendix.tex".into(),
                output_dir: ".latex-cache/appendix".into(),
            },
        ];
        config.latex.preview.document = Some("appendix".into());

        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        serde_yaml::from_str::<serde_yaml::Value>(&content)
            .expect("generated preview Compose must be valid YAML");

        assert!(content.contains("container_name: test-ctr-latex-preview"));
        assert!(content.contains("user: aibox\n    entrypoint: []"));
        assert!(content.contains("${WORKSPACE_DIR:-..}:/workspace:ro"));
        assert!(content.contains("\"127.0.0.1:8765:8765\""));
        assert!(content.contains("/usr/local/bin/aibox-latex-preview"));
        assert!(content.contains("AIBOX_LATEX_PREFERRED_DOCUMENT: \"appendix\""));
        assert!(content.contains("/workspace/.latex-cache/overview/overview.pdf"));
        assert!(content.contains("/workspace/.latex-cache/appendix/appendix.pdf"));
        assert!(content.contains("read_only: true"));
        assert!(content.contains("no-new-privileges:true"));
        assert!(content.contains("cap_drop:\n      - ALL"));
        assert!(content.contains("http://127.0.0.1:8765/health"));
    }

    #[test]
    fn compose_omits_latex_preview_sidecar_when_preview_is_disabled() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.latex.documents.push(crate::config::LatexDocument {
            name: "overview".into(),
            source: "docs/overview.tex".into(),
            output_dir: ".latex-cache/overview".into(),
        });

        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(!content.contains("test-ctr-latex-preview"));
        assert!(!content.contains("AIBOX_LATEX_DOCUMENTS_JSON"));
    }

    #[test]
    fn compose_latex_preview_public_bind_is_explicit() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.latex.preview.enabled = true;
        config.latex.preview.bind = "0.0.0.0".into();
        config.latex.preview.port = 9876;
        config.latex.preview.allow_public = true;
        config.latex.documents.push(crate::config::LatexDocument {
            name: "overview".into(),
            source: "docs/overview.tex".into(),
            output_dir: ".latex-cache/overview".into(),
        });

        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains("\"0.0.0.0:9876:8765\""));
    }

    #[test]
    fn compose_mounts_xdg_state_home() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();

        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(
            content.contains(".local:/root/.local:rw"),
            "compose should mount writable XDG local/state parent for TUIs such as lazygit:\n{content}"
        );
    }

    #[test]
    fn compose_mounts_writable_xdg_cache_home() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();

        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(
            content.contains(".cache:/root/.cache:rw"),
            "compose should mount writable XDG cache home so uv, starship, and tmux can create/read cache directories:\n{content}"
        );
    }

    #[test]
    fn compose_marks_runtime_persistence_mounts_explicitly_writable() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();

        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        for mount in [
            "${WORKSPACE_DIR:-..}:/workspace:rw",
            ".vim:/root/.vim:rw",
            ".tmux:/root/.tmux:rw",
            ".cache:/root/.cache:rw",
            ".config:/root/.config:rw",
            ".local:/root/.local:rw",
        ] {
            assert!(
                content.contains(mount),
                "compose should mark runtime persistence mount {mount} as read-write:\n{content}"
            );
        }
        for stale_mount in [
            ".config/tmux:/root/.config/tmux",
            ".config/starship.toml:/root/.config/starship.toml",
            ".config/yazi:/root/.config/yazi",
            ".config/git:/root/.config/git",
            ".config/state:/root/.config/state",
            ".local/bin:/root/.local/bin",
            ".vim/vimrc:/root/.vim/vimrc",
            ".vim/undo:/root/.vim/undo",
        ] {
            assert!(
                !content.contains(stale_mount),
                "compose should not emit narrow runtime-home mount {stale_mount}; broad parents avoid future cache/config drift:\n{content}"
            );
        }
    }

    #[test]
    fn compose_mounts_starship_prompt_config() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();

        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(
            content.contains(".config:/root/.config:rw")
                && !content.contains(".config/starship.toml:/root/.config/starship.toml"),
            "compose should mount the writable XDG config parent instead of a narrow Starship file mount:\n{content}"
        );
    }

    #[test]
    fn compose_mounts_rust_caches_without_shadowing_cargo_home() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&["rust"], false);
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();

        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains(".cargo/registry:/root/.cargo/registry:rw"));
        assert!(content.contains(".cargo/git:/root/.cargo/git:rw"));
        assert!(
            !content.contains(".cargo:/root/.cargo:rw"),
            "compose must not mount the whole Cargo home; it hides image-provided cargo/rustc shims:\n{content}"
        );
    }

    #[test]
    #[serial]
    fn runtime_dir_scaffold_includes_cache_dirs() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        let host_root = dir.path().join(".aibox-home");

        unsafe {
            std::env::set_var("AIBOX_HOST_ROOT", &host_root);
        }

        crate::seed::ensure_runtime_dirs(&config).unwrap();

        assert!(
            host_root.join(".cache").is_dir()
                && host_root.join(".cache/starship").is_dir()
                && host_root.join(".cache/uv").is_dir()
                && host_root.join(".config/tmux/layouts").is_dir()
                && host_root.join(".tmux/plugins").is_dir(),
            "runtime scaffolding should create the writable cache tree"
        );

        unsafe {
            std::env::remove_var("AIBOX_HOST_ROOT");
        }
    }

    #[test]
    #[serial]
    fn runtime_dir_scaffold_includes_starship_cache_dir() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        let host_root = dir.path().join(".aibox-home");

        unsafe {
            std::env::set_var("AIBOX_HOST_ROOT", &host_root);
        }

        crate::seed::ensure_runtime_dirs(&config).unwrap();

        assert!(
            host_root.join(".cache/starship").is_dir(),
            "runtime scaffolding should create the Starship cache directory"
        );

        unsafe {
            std::env::remove_var("AIBOX_HOST_ROOT");
        }
    }

    #[test]
    fn compose_uses_init_reaper_and_preserves_sleep_command() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();

        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains("init: true"));
        assert!(content.contains("command: sleep infinity"));
    }

    #[test]
    fn compose_main_service_does_not_override_image_user() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();

        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        let main_service = content
            .split("  test-ctr-diagnostics:")
            .next()
            .expect("main service should be present");
        assert!(
            !main_service.contains("\n    user:"),
            "main service must start with the image default user so entrypoint.sh can remap/drop privileges:\n{content}"
        );
    }

    #[test]
    fn compose_exports_shell_env_for_tmux() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();

        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(
            content.contains("SHELL: \"/bin/bash\""),
            "compose should export SHELL so tmux and shell tools do not fall back to /bin/sh:\n{content}"
        );
    }

    #[test]
    fn compose_adds_limited_diagnostics_sidecar() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();

        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains("test-ctr-diagnostics:"));
        assert!(content.contains("container_name: test-ctr-diagnostics"));
        assert!(content.contains("pid: \"service:test-ctr\""));
        assert!(content.contains("pids_limit: 64"));
        assert!(content.contains("mem_limit: 64m"));
        assert!(content.contains("cpus: 0.20"));
        assert!(content.contains("/.aibox:/workspace/.aibox:rw"));
        let diagnostics_service = content
            .split("  test-ctr-diagnostics:")
            .nth(1)
            .expect("diagnostics service should be present");
        assert!(
            !diagnostics_service.contains(":/workspace:rw"),
            "diagnostics sidecar must not mount the whole workspace read-write:\n{content}"
        );
        assert!(content.contains("/usr/local/bin/aibox-diagnostics"));
        assert!(content.contains("/workspace/.aibox/diagnostics"));
    }

    #[test]
    fn compose_adds_seccomp_fallback_when_codex_selected() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.harnesses = vec![crate::config::AiHarness::Codex];
        config.security.acknowledge_seccomp_unconfined = true;
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();

        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains("security_opt:"));
        assert!(content.contains("seccomp=unconfined"));
        assert!(!content.contains("privileged: true"));
        assert!(!content.contains("cap_add:"));
    }

    #[test]
    fn compose_omits_duplicate_seccomp_when_override_already_declares_it() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.harnesses = vec![crate::config::AiHarness::Codex];
        // Override already has seccomp=unconfined, so codex_sandbox_seccomp
        // will be false — no consent required. No need to set
        // acknowledge_seccomp_unconfined here.
        fs::write(
            dir.path().join("docker-compose.override.yml"),
            "services:\n  test-ctr:\n    security_opt:\n      - seccomp=unconfined\n",
        )
        .unwrap();
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();

        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(
            !content.contains("seccomp=unconfined"),
            "generated compose must not duplicate a user override seccomp fallback:\n{content}"
        );
    }

    #[test]
    fn compose_keeps_seccomp_fallback_when_override_declares_it_for_sidecar_only() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.harnesses = vec![crate::config::AiHarness::Codex];
        config.security.acknowledge_seccomp_unconfined = true;
        fs::write(
            dir.path().join("docker-compose.override.yml"),
            "services:\n  unrelated-sidecar:\n    security_opt:\n      - seccomp=unconfined\n",
        )
        .unwrap();
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();

        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(
            content.contains("seccomp=unconfined"),
            "sidecar-only override must not suppress the generated Codex bubblewrap fallback for the main service:\n{content}"
        );
    }

    #[test]
    fn compose_keeps_seccomp_fallback_when_override_only_mentions_it_in_comments() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.harnesses = vec![crate::config::AiHarness::Codex];
        config.security.acknowledge_seccomp_unconfined = true;
        fs::write(
            dir.path().join("docker-compose.override.yml"),
            "services:\n  test-ctr:\n    # security_opt:\n    #   - seccomp=unconfined\n",
        )
        .unwrap();
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();

        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(
            content.contains("seccomp=unconfined"),
            "commented override text must not suppress the generated seccomp fallback:\n{content}"
        );
    }

    #[test]
    fn compose_errors_when_codex_seccomp_needs_consent() {
        // S5 — BR-SEC-HARDEN: without explicit consent, aibox apply must error.
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.harnesses = vec![crate::config::AiHarness::Codex];
        // acknowledge_seccomp_unconfined defaults to false
        let result = generate_docker_compose(&config, dir.path(), &test_env());
        assert!(
            result.is_err(),
            "generate_docker_compose must error when Codex needs seccomp=unconfined but consent is missing"
        );
        let msg = format!("{:#}", result.unwrap_err());
        assert!(
            msg.contains("acknowledge_seccomp_unconfined"),
            "error must reference the consent flag: {msg}"
        );
    }

    #[test]
    fn compose_omits_seccomp_fallback_without_codex() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.harnesses = vec![crate::config::AiHarness::Claude];
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();

        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(!content.contains("seccomp=unconfined"));
    }

    #[test]
    fn devcontainer_does_not_override_compose_command() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();

        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(
            content.contains("\"overrideCommand\": false"),
            "devcontainer clients must preserve the compose command so init=true can reap child processes"
        );
    }

    #[test]
    fn compose_project_and_image_names_are_sanitized() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.container.name = "My.Project_01".to_string();

        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();

        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains("name: my-project-01"));
        assert!(content.contains("image: my-project-01-devcontainer:latest"));
        assert!(content.contains("container_name: My.Project_01"));
    }

    #[test]
    #[serial]
    fn compose_always_references_empty_local_env_file() {
        in_temp_dir(|| {
            let devcontainer = std::path::Path::new(".devcontainer");
            fs::create_dir_all(devcontainer).unwrap();
            let config = make_config(&[], false);

            generate_docker_compose(&config, devcontainer, &test_env()).unwrap();

            let content = fs::read_to_string(devcontainer.join("docker-compose.yml")).unwrap();
            assert!(content.contains("env_file:"));
            assert!(content.contains("- ../.aibox-local.env"));
            assert_eq!(fs::read_to_string(".aibox-local.env").unwrap(), "");
        });
    }

    #[test]
    fn compose_includes_audio_when_enabled() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], true);
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(
            content.contains("PULSE_SERVER"),
            "should have PULSE_SERVER env"
        );
        assert!(
            content.contains("AUDIODRIVER"),
            "should have AUDIODRIVER env"
        );
        assert!(content.contains(".asoundrc"), "should mount .asoundrc");
    }

    #[test]
    fn compose_excludes_audio_when_disabled() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(!content.contains("PULSE_SERVER"));
        assert!(!content.contains("AUDIODRIVER"));
        assert!(!content.contains(".asoundrc"));
    }

    #[test]
    fn dockerfile_appends_local_when_present() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        fs::write(
            dir.path().join("Dockerfile.local"),
            "RUN npx playwright install --with-deps chromium\n",
        )
        .unwrap();
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            content.contains("# Project-specific layers (from Dockerfile.local"),
            "should have local layers comment"
        );
        assert!(
            content.contains("playwright"),
            "should include Dockerfile.local content"
        );
    }

    #[test]
    fn dockerfile_skips_empty_local() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        fs::write(dir.path().join("Dockerfile.local"), "  \n").unwrap();
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            !content.contains("Project-specific layers"),
            "should not include local layers comment for empty file"
        );
    }

    #[test]
    fn dockerfile_works_without_local() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            !content.contains("Project-specific layers"),
            "should not include local layers comment when no Dockerfile.local"
        );
    }

    #[test]
    fn dockerfile_local_with_multistage() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&["python"], false);
        fs::write(
            dir.path().join("Dockerfile.local"),
            "FROM node:20 AS node-builder\nRUN npm ci\n\nFROM aibox\nCOPY --from=node-builder /app /app\n",
        )
        .unwrap();
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(content.contains("FROM node:20 AS node-builder"));
        assert!(content.contains("FROM aibox"));
        assert!(content.contains("COPY --from=node-builder"));
    }

    #[test]
    fn devcontainer_json_python_extension() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&["python"], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("ms-python.python"));
    }

    #[test]
    fn devcontainer_json_latex_extensions() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&["latex"], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("james-yu.latex-workshop"));
        assert!(content.contains("mblode.zotero"));
    }

    #[test]
    fn devcontainer_json_rust_extension() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&["rust"], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("rust-lang.rust-analyzer"));
    }

    #[test]
    fn devcontainer_json_python_latex_extensions() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&["python", "latex"], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("ms-python.python"));
        assert!(content.contains("james-yu.latex-workshop"));
    }

    #[test]
    fn devcontainer_json_typst_extension() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&["typst"], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("myriad-dreamin.tinymist"));
    }

    #[test]
    fn devcontainer_json_python_typst_extensions() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&["python", "typst"], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("ms-python.python"));
        assert!(content.contains("myriad-dreamin.tinymist"));
    }

    #[test]
    fn devcontainer_json_includes_post_create_command() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.container.post_create_command = Some("pip install foo".to_string());
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(
            content.contains("postCreateCommand"),
            "should contain postCreateCommand key"
        );
        assert!(
            content.contains("pip install foo"),
            "should contain the command value"
        );
    }

    #[test]
    fn devcontainer_json_includes_keepalive() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.container.keepalive = true;
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(
            content.contains("postStartCommand"),
            "should contain postStartCommand key"
        );
        assert!(
            content.contains("nslookup"),
            "should contain keepalive nslookup command"
        );
    }

    #[test]
    fn devcontainer_json_excludes_keepalive_when_disabled() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(
            !content.contains("postStartCommand"),
            "should not contain postStartCommand when keepalive is disabled"
        );
    }

    #[test]
    fn devcontainer_json_includes_processkit_gateway_daemon_when_requested() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.mcp.gateway.mode = crate::config::McpGatewayMode::DaemonProxy;
        config.mcp.gateway.lazy_catalog = true;
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("postStartCommand"));
        assert!(content.contains("processkit-gateway/mcp/server.py"));
        assert!(content.contains("streamable-http"));
        assert!(content.contains("catalog --write"));
        assert!(content.contains("UV_CACHE_DIR=/tmp/aibox/uv-cache"));
        assert!(content.contains("PROCESSKIT_GATEWAY_IMPORT_MODE=lazy-catalog"));
    }

    #[test]
    fn devcontainer_json_auto_uses_proxy_owned_gateway_startup_when_installed() {
        let dir = tempfile::tempdir().unwrap();
        let version = crate::processkit_vocab::PROCESSKIT_DEFAULT_VERSION;
        let gateway_dir = dir
            .path()
            .join(crate::processkit_vocab::TEMPLATES_PROCESSKIT_DIR)
            .join(version)
            .join(crate::processkit_vocab::src::CONTEXT_DIR)
            .join(crate::processkit_vocab::src::SKILLS)
            .join("processkit/processkit-gateway/mcp");
        fs::create_dir_all(&gateway_dir).unwrap();
        fs::write(gateway_dir.join("server.py"), "# test stub\n").unwrap();

        let mut config = make_config(&[], false);
        config.processkit.version = version.to_string();
        config.mcp.gateway.mode = crate::config::McpGatewayMode::Auto;
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(
            !content.contains("processkit-gateway/mcp/server.py"),
            "auto mode must rely on processkit v0.25.4 stdio-proxy daemon startup, not devcontainer postStartCommand:\n{content}"
        );
    }

    #[test]
    fn devcontainer_json_auto_omits_gateway_daemon_when_gateway_missing() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.mcp.gateway.mode = crate::config::McpGatewayMode::Auto;
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(!content.contains("processkit-gateway/mcp/server.py"));
    }

    #[test]
    fn devcontainer_json_base_no_extra_extensions() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(!content.contains("ms-python.python"));
        assert!(!content.contains("rust-lang.rust-analyzer"));
        assert!(!content.contains("james-yu.latex-workshop"));
    }

    #[test]
    fn devcontainer_json_compose_override_array() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        // Create an override file
        fs::write(
            dir.path().join("docker-compose.override.yml"),
            "services:\n  postgres:\n    image: postgres:16\n",
        )
        .unwrap();
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        let json: serde_json::Value = serde_json::from_str(
            content
                .lines()
                .filter(|l| !l.starts_with("//"))
                .collect::<Vec<_>>()
                .join("\n")
                .as_str(),
        )
        .unwrap();
        let compose_file = &json["dockerComposeFile"];
        assert!(
            compose_file.is_array(),
            "dockerComposeFile should be an array when override exists, got: {}",
            compose_file
        );
        let arr = compose_file.as_array().unwrap();
        assert_eq!(arr.len(), 2);
        assert_eq!(arr[0], "docker-compose.yml");
        assert_eq!(arr[1], "docker-compose.override.yml");
    }

    #[test]
    fn devcontainer_json_compose_no_override() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        // No override file created
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        let json: serde_json::Value = serde_json::from_str(
            content
                .lines()
                .filter(|l| !l.starts_with("//"))
                .collect::<Vec<_>>()
                .join("\n")
                .as_str(),
        )
        .unwrap();
        let compose_file = &json["dockerComposeFile"];
        assert!(
            compose_file.is_string(),
            "dockerComposeFile should be a string when no override exists, got: {}",
            compose_file
        );
        assert_eq!(compose_file, "docker-compose.yml");
    }

    #[test]
    fn dockerfile_starts_with_header_comment() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        // v0.18.7: header is intentionally version-free to avoid rebuild churn.
        assert!(content.starts_with("# Generated by aibox"));
    }

    #[test]
    fn compose_starts_with_header_comment() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        // v0.18.7: header is intentionally version-free to avoid rebuild churn.
        assert!(content.starts_with("# Generated by aibox"));
    }

    #[test]
    fn devcontainer_json_starts_with_header_comment() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        // v0.18.7: header is intentionally version-free to avoid rebuild churn.
        assert!(content.starts_with("// Generated by aibox"));
    }

    #[test]
    fn devcontainer_json_claude_terminal_profile() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(&[], false);
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(
            content.contains("claude"),
            "default config should include claude profile"
        );
    }

    #[test]
    fn devcontainer_json_no_ai_terminal_profiles_when_empty() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.harnesses = vec![];
        config.resolve_ai_provider_addons();
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(
            !content.contains("claude"),
            "should not have claude profile"
        );
        assert!(!content.contains("aider"), "should not have aider profile");
        assert!(content.contains("bash"), "should still have bash profile");
    }

    #[test]
    fn devcontainer_json_aider_terminal_profile() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.harnesses = vec![crate::config::AiProvider::Aider];
        config.resolve_ai_provider_addons();
        generate_devcontainer_json(&config, dir.path()).unwrap();
        let content = fs::read_to_string(dir.path().join("devcontainer.json")).unwrap();
        assert!(content.contains("aider"), "should have aider profile");
        assert!(
            !content.contains("claude"),
            "should not have claude profile"
        );
    }

    #[test]
    fn dockerfile_includes_aider_install() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.harnesses = vec![crate::config::AiProvider::Aider];
        config.resolve_ai_provider_addons();
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(content.contains("aider"), "should install aider");
        assert!(
            content.contains("uv tool install"),
            "should use uv tool install"
        );
    }

    #[test]
    fn dockerfile_installs_hermes_in_shared_uv_tool_directory() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.harnesses = vec![crate::config::AiProvider::Hermes];
        config.resolve_ai_provider_addons();
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            content.contains("UV_TOOL_DIR=/opt/aibox/uv-tools uv tool install hermes-agent"),
            "Hermes should install into a root-independent shared tool directory: {content}"
        );
        assert!(
            !content.contains("USER aibox\nRUN UV_TOOL_DIR=/opt/aibox/uv-tools"),
            "Hermes install must retain root access to /usr/local/bin: {content}"
        );
    }

    #[test]
    fn dockerfile_installs_tau_in_shared_uv_tool_directory() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.harnesses = vec![crate::config::AiProvider::Tau];
        config.resolve_ai_provider_addons();
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            content.contains("UV_TOOL_DIR=/opt/aibox/uv-tools uv tool install tau-ai==0.4.6"),
            "Tau should be installed from its pinned PyPI package: {content}"
        );
        assert!(
            content.contains("chmod -R a+rX /opt/aibox/uv-tools"),
            "Tau tool environment must be traversable by the runtime user: {content}"
        );
    }

    #[test]
    fn dockerfile_claude_installed_via_addon() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.harnesses = vec![crate::config::AiProvider::Claude];
        config.resolve_ai_provider_addons();
        generate_dockerfile(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            content.contains("downloads.claude.ai/claude-code/apt"),
            "should install Claude from Anthropic's apt repository"
        );
        assert!(
            content.contains("install -m 0755 \"$claude_real\" /usr/local/bin/claude"),
            "Claude install should copy the resolved binary to the stable terminal profile path"
        );
        assert!(!content.contains("aider"), "should not install aider");
        assert!(!content.contains("gemini"), "should not install gemini");
    }

    #[test]
    fn base_image_routes_uv_tool_bins_to_usr_local_bin() {
        let content = include_str!("../../images/base-debian/Dockerfile");
        assert!(
            content.contains("UV_TOOL_BIN_DIR=\"/usr/local/bin\""),
            "base image should route uv tool executables to /usr/local/bin"
        );
    }

    #[test]
    fn base_image_installs_yazi_companion_entrypoint() {
        let content = include_str!("../../images/base-debian/Dockerfile");
        assert!(
            content.contains("ln -sf /usr/local/bin/yazi /usr/local/bin/ya"),
            "base image should expose yazi's companion entrypoint"
        );
    }

    #[test]
    fn base_image_installs_aibox_powerkit_segment() {
        let content = include_str!("../../images/base-debian/Dockerfile");
        assert!(
            content.contains(
                "config/tmux/powerkit-plugins/aibox.sh /usr/local/share/aibox/tmux/plugins/tmux-powerkit/src/plugins/aibox.sh"
            ),
            "base image should inject the aibox runtime segment into the pinned PowerKit tree"
        );
        assert!(
            content.contains(
                "config/tmux/powerkit-plugins/uptime.sh     /usr/local/share/aibox/tmux/plugins/tmux-powerkit/src/plugins/uptime.sh"
            ),
            "base image should override PowerKit uptime with container uptime"
        );
        assert!(
            content.contains(
                "config/tmux/powerkit-plugins/netspeed.sh   /usr/local/share/aibox/tmux/plugins/tmux-powerkit/src/plugins/netspeed.sh"
            ),
            "base image should override PowerKit netspeed with fixed-width rates"
        );
        assert!(
            content.contains(
                "config/tmux/powerkit-plugins/kubernetes.sh /usr/local/share/aibox/tmux/plugins/tmux-powerkit/src/plugins/kubernetes.sh"
            ),
            "base image should override PowerKit kubernetes with local-context-only status"
        );
        assert!(
            content.contains(
                "config/tmux/powerkit-plugins/cloud.sh      /usr/local/share/aibox/tmux/plugins/tmux-powerkit/src/plugins/cloud.sh"
            ),
            "base image should override PowerKit cloud with local-context-only status"
        );
        assert!(
            content.contains(
                "config/tmux/powerkit-plugins/modelstatus_provider.sh /usr/local/share/aibox/tmux/plugins/tmux-powerkit/src/plugins/modelstatus_provider.sh"
            ) && content.contains("modelstatus_${provider}.sh"),
            "base image should install model-provider status plugin wrappers"
        );
    }

    #[test]
    fn base_image_prepares_writable_cache_home_and_shell_env() {
        let content = include_str!("../../images/base-debian/Dockerfile");
        let bashrc = include_str!("../../images/base-debian/config/bashrc");
        assert!(content.contains("SHELL=/bin/bash"));
        assert!(
            content.contains("ENV UV_CACHE_DIR=/tmp/aibox/uv-cache")
                && content.contains("/home/aibox/.cache/starship")
                && content.contains("/home/aibox/.cache/uv")
                && content.contains("/tmp/aibox/uv-cache")
                && content.contains("/home/aibox/.tmux/plugins")
                && content.contains("chown -R aibox:aibox /home/aibox")
                && content.contains("chown -R aibox:aibox /tmp/aibox"),
            "base image should create writable cache-home and uv cache paths before final ownership fix"
        );
        assert!(
            bashrc.contains("moved file blocking Starship cache")
                && bashrc.contains("mkdir -p \"$HOME/.cache/starship\""),
            "interactive Bash must repair a file collision at Starship's cache path before initializing the prompt"
        );
    }

    #[test]
    fn base_entrypoint_reowns_tmp_aibox_after_uid_remap() {
        let content = include_str!("../../images/base-debian/config/entrypoint.sh");
        assert!(
            content.contains("mkdir -p /tmp/aibox/uv-cache")
                && content.contains("chown -R \"$TARGET_UID:$TARGET_GID\" /tmp/aibox"),
            "entrypoint must re-own /tmp/aibox after UID/GID remap so uv caches stay writable:\n{content}"
        );
    }

    #[test]
    fn compose_includes_aider_volume() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.harnesses = vec![crate::config::AiProvider::Aider];
        config.resolve_ai_provider_addons();
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(content.contains(".aider"), "should have aider volume mount");
    }

    #[test]
    fn compose_includes_gemini_volume() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.harnesses = vec![crate::config::AiProvider::Gemini];
        config.resolve_ai_provider_addons();
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(
            content.contains(".gemini"),
            "should have gemini volume mount"
        );
    }

    #[test]
    fn compose_includes_codex_volume() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.harnesses = vec![crate::config::AiProvider::Codex];
        // Codex requires seccomp=unconfined; set the consent flag for the test.
        config.security.acknowledge_seccomp_unconfined = true;
        config.resolve_ai_provider_addons();
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        let expected = format!("../.aibox-home/.codex:{}/.codex", config.container_home());
        assert!(
            content.contains(&expected),
            "should mount the persisted Codex home directory, including auth.json"
        );
    }

    #[test]
    fn compose_no_ai_volumes_when_empty() {
        let dir = tempfile::tempdir().unwrap();
        let mut config = make_config(&[], false);
        config.ai.harnesses = vec![];
        config.resolve_ai_provider_addons();
        generate_docker_compose(&config, dir.path(), &test_env()).unwrap();
        let content = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(
            !content.contains(".claude"),
            "should not have claude volume"
        );
        assert!(!content.contains(".aider"), "should not have aider volume");
        assert!(
            !content.contains(".gemini"),
            "should not have gemini volume"
        );
        assert!(!content.contains(".codex"), "should not have codex volume");
    }
}
